### ISSUE TITLE
运行set_init.py不显示框选界面

### ISSUE THREAD

**Issue by Sunchanghao** [generalized-intelligence/GAAS-Object-Tracking#1]
在ROSKCF.CPP中修改了相机话题后运行set_init.py并不报错　但是也没有任何显示

**Comment by Sunchanghao** [comment]
【已解决】
在６_object_tracking文件夹中　修改config.py 修改里面相机的话题
在KCF/src/RosKCF.cpp的line21修改话题

**Comment by Lee-Siyoung** [comment]
> [해결]
> 6_object_tracking 폴더의 config.py를 수정하여 내부 카메라의 주제
> 를 수정 KCF/src/RosKCF.cpp의 line21 주제 수정

How did you change the camera position?
I tried /webcam/image_raw but failed.
